modLoader="javafml"
license="${mod_license}"
issueTrackerURL="${mod_github}/issues"

[[mods]]
    modId="${mod_id}"
    version="${mod_version}"
    displayName="${mod_name}"
    updateJSONURL="https://api.modrinth.com/updates/better-mcdonalds-mod/forge_updates.json?neoforge=only"
    displayURL="${mod_homepage}"
    logoFile="${mod_icon}"
    credits="Volwert123, rporotos, kohari_nk, sovseabird"
    authors="${mod_author}"
    description='''${mod_description}'''

[[accessTransformers]]
    file="accesstransformer.cfg"

[[dependencies.${mod_id}]]
    modId="neoforge"
    type="required"
    versionRange="[${neoforge_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    type="required"
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="balm"
    type="required"
    versionRange="[${balm_version},)"
    ordering="AFTER"
    side="BOTH"