modLoader="javafml"
loaderVersion="[4,)"
license="mSLA v2.0"
issueTrackerURL="https://github.com/moritz-htk/better-mcdonalds-mod/issues"

[[mods]]
    modId="better_mcdonalds_mod"
    version="${mod_version}"
    displayName="Better McDonald's Mod"
    updateJSONURL="https://api.modrinth.com/updates/better-mcdonalds-mod/forge_updates.json?neoforge=only"
    displayURL="https://kyronis.net/better-mcdonalds-mod"
    logoFile="assets/better_mcdonalds_mod/icon.png"
    credits="Volwert123, rporotos, kohari_nk, sovseabird"
    authors="Kyronis"
    description='''This Minecraft mod adds many new items and food from McDonald's.'''

[[dependencies.better_mcdonalds_mod]]
    modId="neoforge"
    type="required"
    versionRange="[21.8,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.better_mcdonalds_mod]]
    modId="minecraft"
    type="required"
    versionRange="[${minecraft_version}, 1.22)"
    ordering="NONE"
    side="BOTH"

[[dependencies.better_mcdonalds_mod]]
    modId="architectury"
    type="required"
    versionRange="[${architectury_api_version},)"
    ordering="AFTER"
    side="BOTH"

[modproperties.better_mcdonalds_mod]
    catalogueItemIcon="better_mcdonalds_mod:happy_meal"